"""Generate daily recap markdown from positions ledger.

Reads positions.jsonl and produces:
  - reports/paper/recap-YYYY-MM-DD.md   human-readable daily summary
  - Feishu interactive card via notifier (optional, --no-feishu to skip)

Usage:
  python -m quant_trader.scripts.recap --date 2026-07-10
  python -m quant_trader.scripts.recap                       # today (UTC)
  python -m quant_trader.scripts.recap --no-feishu           # skip notification
"""
from __future__ import annotations

import argparse
import json
import logging
import sys
from collections import defaultdict
from datetime import datetime, timezone
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT))

logging.basicConfig(level=logging.INFO, format="%(asctime)s %(levelname)s %(message)s")
log = logging.getLogger("recap")

LEDGER = ROOT / "reports" / "paper" / "positions.jsonl"


def _read_events(path: Path) -> list[dict]:
    if not path.exists():
        return []
    return [json.loads(l) for l in path.read_text().strip().split("\n") if l.strip()]


def _resolve_open(events: list[dict]) -> dict[int, dict]:
    """Resolve final status per id: open+later-closed → closed. open+later-blocked → blocked."""
    by_id: dict[int, dict] = {}
    for e in events:
        eid = int(e["id"])
        if e.get("status") == "open":
            by_id[eid] = e
        elif eid in by_id:
            by_id[eid] = e  # later close/blocked wins
        else:
            by_id[eid] = e
    return by_id


def generate(date: str, ledger_path: Path = LEDGER) -> tuple[Path, dict]:
    """Generate recap for `date` (YYYY-MM-DD, UTC). Returns (path, stats)."""
    events = _read_events(ledger_path)
    resolved = _resolve_open(events)

    closed_today = []
    blocked_today = []
    for eid, ev in resolved.items():
        if ev.get("status") == "closed" and ev.get("exit_ts", "").startswith(date):
            closed_today.append(ev)
        elif ev.get("status") == "blocked" and ev.get("open_day") == date:
            blocked_today.append(ev)

    pnls = [e.get("pnl_pct_lev", 0.0) or 0.0 for e in closed_today]
    realized = sum(pnls)
    wins = [p for p in pnls if p > 0]
    losses = [p for p in pnls if p < 0]
    win_rate = len(wins) / len(pnls) * 100 if pnls else 0
    avg_win = sum(wins) / len(wins) if wins else 0
    avg_loss = sum(losses) / len(losses) if losses else 0
    profit_factor = abs(sum(wins) / sum(losses)) if losses else float("inf")

    open_today = []
    for eid, ev in resolved.items():
        if ev.get("status") == "open" and ev.get("open_day") == date:
            open_today.append(ev)

    # Per-symbol aggregation for closed trades
    per_sym: dict[str, list[float]] = defaultdict(list)
    for e in closed_today:
        per_sym[e["symbol"]].append(e.get("pnl_pct_lev", 0.0) or 0.0)

    out = ROOT / "reports" / "paper" / f"recap-{date}.md"
    lines = [
        f"# Daily Recap - {date}",
        "",
        f"_Generated as-of {date} (UTC)_",
        "",
        f"**Aggregate**: realized={realized*100:+.2f}%  trades={len(closed_today)}  blocked={len(blocked_today)}  opens={len(open_today)}",
        "",
        f"**Win rate**: {win_rate:.1f}%  ({len(wins)}W / {len(losses)}L)",
        f"**Avg win**: {avg_win*100:+.2f}%  |  **Avg loss**: {avg_loss*100:+.2f}%  |  **Profit Factor**: {profit_factor:.2f}",
        "",
        f"## Closed trades ({len(closed_today)})",
        "",
        "| id | symbol | strategy | entry_price | exit_price | reason | pnl% (lev) |",
        "| ---: | --- | --- | ---: | ---: | :---: | ---: |",
    ]
    for e in sorted(closed_today, key=lambda x: x.get("exit_ts", "")):
        pnl = e.get("pnl_pct_lev", 0.0) or 0.0
        sym_s = e["symbol"].replace("/USDT:USDT", "")
        lines.append(
            f"| {e['id']} | {sym_s} | {e['strategy']} | "
            f"{e['entry_price']:.6f} | {e['exit_price']:.6f} | "
            f"{e['exit_reason']} | {pnl*100:+.2f}% |"
        )

    if blocked_today:
        lines += ["", f"## Blocked by risk ({len(blocked_today)})", ""]
        reasons: dict[str, int] = defaultdict(int)
        for e in blocked_today:
            reasons[e.get("block_reason", "?")] += 1
        for r, c in sorted(reasons.items(), key=lambda x: -x[1]):
            lines.append(f"- `{r}` × {c}")

    if open_today:
        lines += ["", f"## Open positions from today ({len(open_today)})", ""]
        for e in open_today:
            sym_s = e["symbol"].replace("/USDT:USDT", "")
            lines.append(f"- id={e['id']} {sym_s} @ `{e['entry_price']:.6f}`")

    lines += [
        "",
        "---",
        "",
        f"_pump_pullback v1.2 | backtest walk-forward 70/30 | generated by quant_trader.scripts.recap_",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    log.info("wrote %s", out)

    stats = {
        "date": date,
        "realized_pct": round(realized * 100, 2),
        "trades": len(closed_today),
        "blocked": len(blocked_today),
        "open_today": len(open_today),
        "win_rate": round(win_rate, 1),
        "avg_win_pct": round(avg_win * 100, 2),
        "avg_loss_pct": round(avg_loss * 100, 2),
        "profit_factor": round(profit_factor, 2),
        "per_symbol": {s.replace("/USDT:USDT", ""): round(sum(p), 2) for s, p in per_sym.items()},
    }
    return out, stats


def send_feishu(stats: dict, webhook_url: str = None) -> bool:
    """Send daily recap to Feishu webhook."""
    try:
        from quant_trader.execution.notifier import FeishuNotifier
    except ImportError:
        log.warning("notifier module not available")
        return False

    # Build card
    realized = stats["realized_pct"]
    if realized > 5:
        template = "green"
    elif realized > 0:
        template = "blue"
    else:
        template = "red"

    elements = [
        {
            "tag": "div",
            "fields": [
                {"is_short": True, "text": {"tag": "lark_md",
                 "content": f"**📈 今日已实现**\n{realized:+.2f}%"}},
                {"is_short": True, "text": {"tag": "lark_md",
                 "content": f"**🎯 胜率**\n{stats['win_rate']:.1f}%"}},
                {"is_short": True, "text": {"tag": "lark_md",
                 "content": f"**📊 交易数**\n{stats['trades']}"}},
                {"is_short": True, "text": {"tag": "lark_md",
                 "content": f"**⛔ 风控阻挡**\n{stats['blocked']}"}},
            ],
        },
        {"tag": "hr"},
        {
            "tag": "div",
            "text": {"tag": "lark_md", "content": (
                f"**Profit Factor**: {stats['profit_factor']:.2f}  |  "
                f"**Avg Win**: {stats['avg_win_pct']:+.2f}%  |  "
                f"**Avg Loss**: {stats['avg_loss_pct']:+.2f}%"
            )},
        },
    ]
    if stats.get("per_symbol"):
        elements.append({"tag": "hr"})
        per_sym_lines = []
        for sym, total in sorted(stats["per_symbol"].items(), key=lambda x: -x[1])[:10]:
            per_sym_lines.append(f"`{sym}`: {total:+.2f}%")
        elements.append({
            "tag": "div",
            "text": {"tag": "lark_md", "content": "**币种 Top10**\n" + "\n".join(per_sym_lines)},
        })

    elements.append({
        "tag": "note",
        "elements": [{"tag": "plain_text",
                      "content": f"⏱ {stats['date']} 02:00 UTC · pump_pullback v1.2 每日回顾"}],
    })

    card = {
        "msg_type": "interactive",
        "card": {
            "header": {
                "title": {"tag": "plain_text", "content": f"📊 每日复盘 | {stats['date']}"},
                "template": template,
            },
            "elements": elements,
        },
    }

    feishu = FeishuNotifier(webhook_url=webhook_url)
    return feishu.send_card(card)


def main():
    p = argparse.ArgumentParser()
    p.add_argument("--date", help="UTC date YYYY-MM-DD (default: today)")
    p.add_argument("--no-feishu", action="store_true", help="skip Feishu notification")
    args = p.parse_args()

    date = args.date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    out, stats = generate(date)

    if not args.no_feishu:
        ok = send_feishu(stats)
        log.info("feishu: %s", "sent" if ok else "skipped/failed")

    print(out.read_text(encoding="utf-8"))


if __name__ == "__main__":
    main()